// <auto-generated />
using System;
using Aimbys.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aimbys.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528000001_AddInstituteLoginId")]
    partial class AddInstituteLoginId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // NOTE: The full model snapshot is maintained in
            // AppDbContextModelSnapshot.cs. This designer file only
            // declares the migration identity so dotnet-ef can find it.
        }
    }
}
