namespace Aimbys.Application.DocumentRendering;

/// <summary>
/// Payload returned by <c>IDocumentRenderService</c>. Carries the
/// generated bytes plus the metadata a controller needs to stream
/// them straight back to the caller (<c>FileStreamResult</c>).
///
/// <para>
/// <see cref="Content"/> is owned by the caller &mdash; the rendering
/// service hands ownership over and never disposes the stream itself.
/// MVC's <c>FileStreamResult</c> disposes after the response is
/// flushed, so no extra plumbing is needed in the typical path.
/// </para>
/// </summary>
/// <param name="Content">Stream positioned at zero, ready to read.</param>
/// <param name="FileName">Suggested download filename including extension.</param>
/// <param name="ContentType">RFC-2045 media type (e.g. <c>"text/html"</c>, <c>"application/pdf"</c>).</param>
public sealed record RenderedDocument(
    Stream Content,
    string FileName,
    string ContentType);
