using Aimbys.Domain.Enums;

namespace Aimbys.Application.Storage;

/// <summary>
/// Marker interface for the local-disk binding of
/// <see cref="IFileStorageService"/>. Most code should depend on the parent
/// interface so the cloud adapter can drop in transparently; this interface
/// exists for the rare site that has to know it is talking to local disk
/// (e.g. orphan-cleanup utilities that walk the filesystem directly, or
/// services that produce trusted server-side bytes that bypass the
/// IFormFile + MIME-validation upload contract).
/// </summary>
public interface ILocalFileStorageService : IFileStorageService
{
    /// <summary>
    /// Persists trusted server-generated bytes (e.g. a result-archive
    /// JSON snapshot, a PDF rendered by the document service) under the
    /// given <paramref name="area"/> and writes a <c>FileAsset</c> audit
    /// row. Unlike <see cref="IFileStorageService.SaveAsync"/> this path
    /// does <em>not</em> validate against a MIME allow-list because the
    /// caller produced the bytes themselves.
    ///
    /// <para>
    /// <paramref name="actorUserId"/> is stored verbatim on the
    /// <c>FileAsset.UploadedByUserId</c> column. Pass <c>"system"</c> for
    /// background-job archives that have no human actor.
    /// </para>
    /// </summary>
    Task<FileSaveResult> SaveBytesAsync(
        FileArea area,
        string ownerKey,
        string fileName,
        string contentType,
        byte[] bytes,
        Guid? instituteId,
        string actorUserId,
        CancellationToken cancellationToken = default);
}
